### PR TITLE
initial backbone for react components

### PR DESCRIPTION
**Pull request by tlee0818**
components

### CODE REVIEW

**Review by khushi02 — COMMENTED** [review]
Code looks good to me, but when I'm running it I'm getting errors. I'll send you the details.

**Comment by tlee0818** [comment]
> Code looks good to me, but when I'm running it I'm getting errors. I'll send you the details.

should be fixed with this new push

**Comment by tlee0818** [comment]
@khushi02 there's a problem with the linkt, cuz the lint json is looking for ts linters, but the project is in just js. did you mean to do this?

**Comment by khushi02** [comment]
Just pushed some changes to fix the typescript stuff.

**Pull request merged**
